[tool.poetry]
name = "websocket-test"
version = "0.1.0"
description = ""
authors = ["Hojung Yun <hojung.yun@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
websockets = "^12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
